import os

CLASSIFICATION_MODEL_WEIGHTS_PATH = os.getenv('CLASSIFICATION_MODEL_WEIGHTS_PATH')
CLASSIFICATION_MODEL_CONFIG_PATH = os.getenv('CLASSIFICATION_MODEL_CONFIG_PATH')

UNET_MODEL_WEIGHTS_PATH = os.getenv('UNET_MODEL_WEIGHTS_PATH')
UNET_MODEL_CONFIG_PATH = os.getenv('UNET_MODEL_CONFIG_PATH')
