export const ADD_FILE = 'ADD_FILE'

export const DELETE_FILE = 'DELETE_FILE'
export const DELETE_ALL_FILE = 'DELETE_ALL_FILE'
export const UPDATE_FILE = 'UPDATE_FILE'


export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR'
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR'
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR'
