name: Deploy app_server to Docker Hub


on:
  push:
    paths:
      - 'app_server/**'
    branches: [ main ]
    
jobs:
  deploy:
    env:
      workdir: ./app_server
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Publish to Docker Hub"
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: dumaevrinat/lungs_diseases
        workdir: ${{env.workdir}}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
